{
 "title": "Ray Serve Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per minute (RPM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second (QPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis Cache Miss Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(rate(redis_keyspace_misses_total[1m]) \n/\n (rate(redis_keyspace_hits_total[1m]) + rate(redis_keyspace_misses_total[1m]))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Cache Hit Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "(rate(redis_keyspace_hits_total[1m]) \n/\n (rate(redis_keyspace_hits_total[1m]) + rate(redis_keyspace_misses_total[1m]))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ray Serve Replica Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_replica_healthy)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m])\n/\nrate(http_request_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests != 200 status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status!=\"2xx\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Memory Usage (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    { "expr": "avg(DCGM_FI_DEV_FB_USED)", "legendFormat": "__auto" }
   ]
  }
 ]
}